version: "3.8"

services:
  powerplant-coding-challenge:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      FLASK_ENV: ${FLASK_ENV}
